//===========================================================
// fw_update.c -- serial dual-partition update orchestrator (see fw_update.h)
//===========================================================

#include "fw_update.h"
#include "xmodem.h"
#include "dspic33ak_nvm.h"

//-----------------------------------------------------------
// Usable image size. The partition is 256 KB (0x40000). Its final 512-byte row
// (0x3FE00..0x3FFFF) contains the BTSEQ word (0x3FFF0) that fw_commit() stamps to
// commit the swap -- so the receiver must never program that row. Cap the image so it
// can never reach it: usable = partition - one row = 0x3FE00.
//-----------------------------------------------------------
#define FW_PARTITION_BYTES      UINT32_C(0x40000)
#define FW_MAX_IMAGE_BYTES      (FW_PARTITION_BYTES - DSPIC33AK_NVM_ROW_BYTES)   // 0x3FE00

// reflash_image.bin manifest, generated by tools/extract_p1_image.py. The file
// LEADS with this packed 16-byte little-endian record, followed by the payload:
//   "DBFW", version=2, project_id=0x3448, payload_bytes, crc16, ~crc16.
// This is a format/integrity gate (not authentication): *fca5 stays blocked for
// an arbitrary, truncated, or wrong-project file even if transport CRCs pass.
//
// WHY THE MANIFEST LEADS (v2) RATHER THAN TRAILS (v1): XMODEM has no file-length
// field, so a sender MUST pad its final block out to the full block size (128 or
// 1024), conventionally with 0x1A (CP/M EOF) -- see the note on bytes_received in
// xmodem.h. A trailing manifest is therefore only "the last 16 bytes received"
// when the file size happens to be a multiple of the sender's block size: true
// for a 128-byte-aligned file under 128-byte blocks, FALSE under XMODEM-1K, which
// broke v1 on real hardware. Leading with the manifest makes payload_bytes known
// before any payload byte arrives, so block size and file alignment stop
// mattering and trailing pad bytes are simply read and discarded.
//
// Version 2 also fails closed in both directions against v1 without any special
// case: a v2 file sent to v1 firmware has no magic in its last 16 bytes, and a v1
// file sent to this firmware has no magic at offset 0.
#define FW_PACKAGE_MANIFEST_BYTES (16u)
#define FW_PACKAGE_VERSION        (2u)
#define FW_PACKAGE_PROJECT_ID     (UINT16_C(0x3448))
#define FW_PACKAGE_MAGIC_0        ((uint8_t)'D')
#define FW_PACKAGE_MAGIC_1        ((uint8_t)'B')
#define FW_PACKAGE_MAGIC_2        ((uint8_t)'F')
#define FW_PACKAGE_MAGIC_3        ((uint8_t)'W')

// How much sender block-padding to tolerate after the payload ends. This receiver
// accepts 128- and 1024-byte blocks, so standard padding is at most 1023 bytes;
// allowing two blocks' worth also absorbs a non-standard sender that appends a
// whole extra pad block, while still bounding an endlessly-streaming sender rather
// than accepting it silently. Keep in sync with PACKAGE_MAX_TRAILING_PAD in
// tools/extract_p1_image.py.
#define FW_PACKAGE_MAX_TRAILING_PAD (2048u)

//-----------------------------------------------------------
// Receive/program context, shared between the XMODEM sink and the finalizer.
//-----------------------------------------------------------
typedef struct
{
    union
    {
        uint8_t  b[DSPIC33AK_NVM_ROW_BYTES];        // 512 bytes, byte view
        uint32_t w[DSPIC33AK_NVM_U32_PER_ROW];      // 128 u32, RowProgram source (aligned)
    } row;
    uint16_t           row_fill;        // bytes currently in row.b
    uint32_t           row_base_off;    // flash offset of row.b[0] (== payload bytes flushed)
    uint32_t           bytes_rx;        // total bytes delivered by the sink (manifest + payload + pad)
    uint32_t           pages_erased;
    uint32_t           rows_programmed;
    uint16_t           img_crc;         // running CRC-16 over programmed rows
    uint8_t            hdr[FW_PACKAGE_MANIFEST_BYTES];
    uint8_t            hdr_fill;        // manifest bytes collected (0..16)
    uint32_t           payload_bytes;   // from the manifest: exact payload length
    uint32_t           payload_seen;    // payload bytes accepted so far (<= payload_bytes)
    uint32_t           trailing_pad;    // bytes received after the payload ended
    uint16_t           payload_crc;     // running CRC-16 over payload bytes only
    uint16_t           expected_crc;    // from the manifest
    uint8_t            last_wrec;
    fw_update_status_t status;          // first error encountered (OK until then)
} fw_ctx_t;

static fw_ctx_t s_ctx;

// True only after a receive that finished FW_UPDATE_OK -- i.e.
// the inactive partition holds a project-tagged, CRC/read-back-verified image. This is the
// gate fw_commit() checks: it must never stamp BTSEQ over an unverified partition
// or after a failed/absent receive.
static bool s_last_receive_good = false;

// Optional display hook (see fw_update.h). NULL = no progress reporting.
static fw_update_progress_fn s_progress = NULL;

void fw_update_set_progress( fw_update_progress_fn fn )
{
    s_progress = fn;
}

bool fw_update_receive_verified(void)
{
    return s_last_receive_good;
}

bool fw_update_claim_verified_receive(void)
{
    bool verified = s_last_receive_good;
    s_last_receive_good = false;
    return verified;
}

static void fw_ctx_reset( fw_ctx_t* c )
{
    c->row_fill        = 0u;
    c->row_base_off    = 0u;
    c->bytes_rx        = 0u;
    c->pages_erased    = 0u;
    c->rows_programmed = 0u;
    c->img_crc         = 0u;
    c->hdr_fill        = 0u;
    c->payload_bytes   = 0u;
    c->payload_seen    = 0u;
    c->trailing_pad    = 0u;
    c->payload_crc     = 0u;
    c->expected_crc    = 0u;
    c->last_wrec       = 0u;
    c->status          = FW_UPDATE_OK;
}

static uint16_t fw_le16(const uint8_t *p)
{
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}

static uint32_t fw_le32(const uint8_t *p)
{
    return (uint32_t)p[0] |
           ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

// Parse and gate the 16-byte leading manifest, the moment its last byte lands.
// Runs BEFORE any erase or program, so a wrong-project / oversized / malformed
// package is refused without having touched the inactive partition at all.
static fw_update_status_t fw_validate_header(fw_ctx_t *c)
{
    uint16_t version;
    uint16_t project_id;
    uint16_t expected_crc_inv;

    if ((c->hdr[0] != FW_PACKAGE_MAGIC_0) || (c->hdr[1] != FW_PACKAGE_MAGIC_1) ||
        (c->hdr[2] != FW_PACKAGE_MAGIC_2) || (c->hdr[3] != FW_PACKAGE_MAGIC_3))
    {
        return FW_UPDATE_ERR_IMAGE_FORMAT;
    }

    version          = fw_le16(&c->hdr[4]);
    project_id       = fw_le16(&c->hdr[6]);
    c->payload_bytes = fw_le32(&c->hdr[8]);
    c->expected_crc  = fw_le16(&c->hdr[12]);
    expected_crc_inv = fw_le16(&c->hdr[14]);

    if ((version != FW_PACKAGE_VERSION) ||
        (project_id != FW_PACKAGE_PROJECT_ID) ||
        (c->payload_bytes == 0u))
    {
        return FW_UPDATE_ERR_IMAGE_FORMAT;
    }
    // Refuse up front rather than failing partway through the write.
    if (c->payload_bytes > FW_MAX_IMAGE_BYTES)
    {
        return FW_UPDATE_ERR_OVERFLOW;
    }
    if ((uint16_t)(c->expected_crc ^ expected_crc_inv) != UINT16_C(0xFFFF))
    {
        return FW_UPDATE_ERR_IMAGE_CRC;
    }
    return FW_UPDATE_OK;
}

// End-of-transfer gate: the manifest must have been complete, the payload must
// have arrived in full (not truncated), and it must match the manifest's CRC.
static fw_update_status_t fw_validate_package(fw_ctx_t *c)
{
    if ((c->hdr_fill != FW_PACKAGE_MANIFEST_BYTES) ||
        (c->payload_seen != c->payload_bytes))
    {
        return FW_UPDATE_ERR_IMAGE_FORMAT;
    }
    return (c->expected_crc == c->payload_crc) ? FW_UPDATE_OK : FW_UPDATE_ERR_IMAGE_CRC;
}

//-----------------------------------------------------------
// Program the current row buffer to the inactive partition and verify it.
// The remainder (if any) is padded with 0xFF first. Rows are written strictly
// sequentially, so the page containing a row is erased exactly when the row is
// the first of its 4 KB page (row_base_off page-aligned). Updates the running
// image CRC over the full (padded) row so it matches the later read-back CRC.
//-----------------------------------------------------------
static fw_update_status_t fw_flush_row( fw_ctx_t* c )
{
    uint32_t active_addr;
    uint32_t inactive_addr;
    dspic33ak_nvm_status_t s;

    while ( c->row_fill < DSPIC33AK_NVM_ROW_BYTES )
    {
        c->row.b[c->row_fill++] = 0xFFu;
    }

    active_addr   = DSPIC33AK_NVM_ACTIVE_BASE + c->row_base_off;
    inactive_addr = DSPIC33AK_NVM_TO_INACTIVE( active_addr );

    // Erase the page the first time we touch it (row_base_off is page-aligned
    // for the first row of every page, and rows arrive in order).
    if ( ( c->row_base_off % DSPIC33AK_NVM_PAGE_BYTES ) == 0u )
    {
        s = DSPIC33AK_NVM_PageErase( inactive_addr );
        c->last_wrec = DSPIC33AK_NVM_LastWrec();
        if ( s != DSPIC33AK_NVM_OK )
        {
            return FW_UPDATE_ERR_NVM;
        }
        c->pages_erased++;
    }

    s = DSPIC33AK_NVM_RowProgram( inactive_addr, c->row.w );
    c->last_wrec = DSPIC33AK_NVM_LastWrec();
    if ( s != DSPIC33AK_NVM_OK )
    {
        return FW_UPDATE_ERR_NVM;
    }

    s = DSPIC33AK_NVM_Verify( inactive_addr, c->row.b, DSPIC33AK_NVM_ROW_BYTES );
    if ( s != DSPIC33AK_NVM_OK )
    {
        return FW_UPDATE_ERR_NVM;
    }

    c->img_crc = xmodem_crc16_cont( c->img_crc, c->row.b, DSPIC33AK_NVM_ROW_BYTES );
    c->rows_programmed++;
    c->row_base_off += DSPIC33AK_NVM_ROW_BYTES;
    c->row_fill = 0u;
    return FW_UPDATE_OK;
}

//-----------------------------------------------------------
// XMODEM data sink: accept bytes strictly in order. The first 16 bytes are the
// manifest (which tells us the exact payload length); the next payload_bytes are
// the image, buffered into rows and flushed when full; anything after that is the
// sender's block padding and is discarded rather than written to flash.
// Returns non-zero to abort the transfer; the specific reason is left in
// c->status so the caller can report it.
//-----------------------------------------------------------
static int fw_sink( uint32_t off, const uint8_t* data, uint16_t len, void* vctx )
{
    fw_ctx_t* c = (fw_ctx_t*)vctx;
    uint16_t  i;

    // We accumulate sequentially; the offset must match what we've accepted.
    if ( off != c->bytes_rx )
    {
        c->status = FW_UPDATE_ERR_XMODEM;
        return 1;
    }
    // No total-length guard here: bytes_rx legitimately covers manifest + payload
    // + sender padding. The payload itself is capped by fw_validate_header()
    // before the first payload byte is ever written.

    for ( i = 0u; i < len; i++ )
    {
        if ( c->hdr_fill < FW_PACKAGE_MANIFEST_BYTES )
        {
            c->hdr[c->hdr_fill++] = data[i];
            if ( c->hdr_fill == FW_PACKAGE_MANIFEST_BYTES )
            {
                fw_update_status_t s = fw_validate_header( c );
                if ( s != FW_UPDATE_OK )
                {
                    c->status = s;
                    return 1;
                }
            }
            continue;
        }

        if ( c->payload_seen >= c->payload_bytes )
        {
            // Sender block padding (0x1A ...) past the end of the real image.
            // Tolerate a bounded amount; never program it.
            c->trailing_pad++;
            if ( c->trailing_pad > FW_PACKAGE_MAX_TRAILING_PAD )
            {
                c->status = FW_UPDATE_ERR_IMAGE_FORMAT;
                return 1;
            }
            continue;
        }

        c->payload_crc = xmodem_crc16_cont( c->payload_crc, &data[i], 1u );
        c->payload_seen++;
        c->row.b[c->row_fill++] = data[i];
        if ( c->row_fill == DSPIC33AK_NVM_ROW_BYTES )
        {
            fw_update_status_t s = fw_flush_row( c );
            if ( s != FW_UPDATE_OK )
            {
                c->status = s;
                return 1;
            }
        }
    }

    c->bytes_rx += len;

    // One notification per block. Cheap by contract, and deliberately after the
    // block's bytes are programmed so the display reflects flash, not just RX.
    if ( s_progress != NULL )
    {
        s_progress( c->payload_seen, c->payload_bytes );
    }
    return 0;
}

//-----------------------------------------------------------
// Read the programmed span back word by word and CRC-16 it. PASS iff it matches
// the running image CRC. Proves the inactive-alias read-back path on silicon.
//-----------------------------------------------------------
static fw_update_status_t fw_readback_crc( fw_ctx_t* c, uint16_t* out_crc )
{
    uint32_t total = c->rows_programmed * DSPIC33AK_NVM_ROW_BYTES;
    uint32_t a;
    uint16_t crc = 0u;

    for ( a = 0u; a < total; a += DSPIC33AK_NVM_WORD_BYTES )
    {
        uint32_t w[DSPIC33AK_NVM_U32_PER_WORD];
        uint32_t inactive_addr = DSPIC33AK_NVM_TO_INACTIVE( DSPIC33AK_NVM_ACTIVE_BASE + a );
        if ( DSPIC33AK_NVM_ReadWord( inactive_addr, w ) != DSPIC33AK_NVM_OK )
        {
            return FW_UPDATE_ERR_NVM;
        }
        crc = xmodem_crc16_cont( crc, (const uint8_t*)w, DSPIC33AK_NVM_WORD_BYTES );
    }

    *out_crc = crc;
    return ( crc == c->img_crc ) ? FW_UPDATE_OK : FW_UPDATE_ERR_READBACK;
}

//-----------------------------------------------------------
// Flush any partial final row, require >= 1 row, then read-back-verify.
//-----------------------------------------------------------
static fw_update_status_t fw_finalize( fw_ctx_t* c, uint16_t* readback_crc )
{
    *readback_crc = 0u;

    if ( c->status != FW_UPDATE_OK )
    {
        return c->status;                       // the sink already failed
    }
    c->status = fw_validate_package(c);
    if (c->status != FW_UPDATE_OK)
    {
        return c->status;
    }
    if ( c->row_fill > 0u )
    {
        fw_update_status_t s = fw_flush_row( c );
        if ( s != FW_UPDATE_OK )
        {
            c->status = s;
            return s;
        }
    }
    if ( c->rows_programmed == 0u )
    {
        c->status = FW_UPDATE_ERR_XMODEM;       // nothing arrived
        return c->status;
    }

    c->status = fw_readback_crc( c, readback_crc );
    return c->status;
}

static void fw_fill_result( const fw_ctx_t* c, uint16_t readback_crc, fw_update_result_t* out )
{
    if ( out == NULL )
    {
        return;
    }
    out->status          = c->status;
    out->bytes_rx        = c->bytes_rx;
    out->pages_erased    = c->pages_erased;
    out->rows_programmed = c->rows_programmed;
    out->img_crc         = c->img_crc;
    out->readback_crc    = readback_crc;
    out->payload_crc     = c->payload_crc;
    out->last_wrec       = c->last_wrec;
}

//-----------------------------------------------------------
// Public API
//-----------------------------------------------------------
fw_update_status_t fw_update_receive( fw_update_result_t* out )
{
    uint16_t        readback_crc = 0u;
    uint32_t        rx           = 0u;
    xmodem_status_t xs;

    fw_ctx_reset( &s_ctx );
    s_last_receive_good = false;                // invalidate any prior commit gate

    // The caller invokes this from the foreground command processor and pauses
    // all periodic application output first. While this blocking function owns
    // UART1, no printf/write path may run: XMODEM control bytes (C/ACK/NAK) must
    // be the only board-to-host traffic until the transfer finishes.

    xs = xmodem_receive( fw_sink, &s_ctx, &rx );

    if ( s_ctx.status != FW_UPDATE_OK )
    {
        // The sink aborted; its reason is already in s_ctx.status. Nothing more.
    }
    else if ( xs != XMODEM_OK )
    {
        s_ctx.status = FW_UPDATE_ERR_XMODEM;
    }
    else
    {
        (void)fw_finalize( &s_ctx, &readback_crc );
    }

    // Arm the commit gate ONLY for a receive that finished OK -- the inactive
    // partition now holds a project-tagged, CRC/read-back-verified image.
    s_last_receive_good = ( s_ctx.status == FW_UPDATE_OK );

    fw_fill_result( &s_ctx, readback_crc, out );
    return s_ctx.status;
}
