//===========================================================
// fw_update.c -- serial Dual Bank update orchestrator (see fw_update.h)
//===========================================================

#include "fw_update.h"
#include "xmodem.h"
#include "dspic33ak_nvm.h"

//-----------------------------------------------------------
// Usable image size. The partition is 256 KB (0x40000). Its final 512-byte row
// (0x3FE00..0x3FFFF) contains the BTSEQ word (0x3FFF0) that fw_commit() stamps to
// commit the swap -- so the receiver must never program that row. Cap the image so it
// can never reach it: usable = partition - one row = 0x3FE00.
//-----------------------------------------------------------
#define FW_PARTITION_BYTES      UINT32_C(0x40000)
#define FW_MAX_IMAGE_BYTES      (FW_PARTITION_BYTES - DSPIC33AK_NVM_ROW_BYTES)   // 0x3FE00

// reflash_image.bin trailer, generated by tools/extract_p1_image.py. The file is
// XMODEM-block aligned and ends with this packed 16-byte little-endian record:
//   "DBFW", version=1, project_id=0x3448, payload_bytes, crc16, ~crc16.
// This is a format/integrity gate (not authentication): *fca5 stays blocked for
// an arbitrary, truncated, or wrong-project file even if transport CRCs pass.
#define FW_PACKAGE_TRAILER_BYTES  (16u)
#define FW_PACKAGE_VERSION        (1u)
#define FW_PACKAGE_PROJECT_ID     (UINT16_C(0x3448))
#define FW_PACKAGE_MAGIC_0        ((uint8_t)'D')
#define FW_PACKAGE_MAGIC_1        ((uint8_t)'B')
#define FW_PACKAGE_MAGIC_2        ((uint8_t)'F')
#define FW_PACKAGE_MAGIC_3        ((uint8_t)'W')

//-----------------------------------------------------------
// Receive/program context, shared between the XMODEM sink and the finalizer.
//-----------------------------------------------------------
typedef struct
{
    union
    {
        uint8_t  b[DSPIC33AK_NVM_ROW_BYTES];        // 512 bytes, byte view
        uint32_t w[DSPIC33AK_NVM_U32_PER_ROW];      // 128 u32, RowProgram source (aligned)
    } row;
    uint16_t           row_fill;        // bytes currently in row.b
    uint32_t           row_base_off;    // image offset of row.b[0] (== bytes flushed)
    uint32_t           bytes_rx;        // total payload bytes accepted from the sink
    uint32_t           pages_erased;
    uint32_t           rows_programmed;
    uint16_t           img_crc;         // running CRC-16 over programmed rows
    uint16_t           package_crc;     // CRC over all received bytes except final trailer
    uint8_t            package_tail[FW_PACKAGE_TRAILER_BYTES];
    uint8_t            package_tail_count;
    uint8_t            package_tail_pos; // oldest byte when tail_count == trailer size
    uint8_t            last_wrec;
    fw_update_status_t status;          // first error encountered (OK until then)
} fw_ctx_t;

static fw_ctx_t s_ctx;

// True only after a receive that finished FW_UPDATE_OK -- i.e.
// the inactive partition holds a project-tagged, CRC/read-back-verified image. This is the
// gate fw_commit() checks: it must never stamp BTSEQ over an unverified partition
// or after a failed/absent receive.
static bool s_last_receive_good = false;

bool fw_update_receive_verified(void)
{
    return s_last_receive_good;
}

bool fw_update_claim_verified_receive(void)
{
    bool verified = s_last_receive_good;
    s_last_receive_good = false;
    return verified;
}

static void fw_ctx_reset( fw_ctx_t* c )
{
    c->row_fill        = 0u;
    c->row_base_off    = 0u;
    c->bytes_rx        = 0u;
    c->pages_erased    = 0u;
    c->rows_programmed = 0u;
    c->img_crc         = 0u;
    c->package_crc     = 0u;
    c->package_tail_count = 0u;
    c->package_tail_pos   = 0u;
    c->last_wrec       = 0u;
    c->status          = FW_UPDATE_OK;
}

// Delay the package CRC by 16 bytes. At EOT, package_tail therefore contains
// exactly the trailer while package_crc covers every byte before it. No complete
// image needs to be retained in RAM.
static void fw_package_track_byte(fw_ctx_t *c, uint8_t byte)
{
    if (c->package_tail_count < FW_PACKAGE_TRAILER_BYTES)
    {
        c->package_tail[c->package_tail_count++] = byte;
        return;
    }

    c->package_crc = xmodem_crc16_cont(c->package_crc,
                                        &c->package_tail[c->package_tail_pos], 1u);
    c->package_tail[c->package_tail_pos] = byte;
    c->package_tail_pos++;
    if (c->package_tail_pos >= FW_PACKAGE_TRAILER_BYTES)
    {
        c->package_tail_pos = 0u;
    }
}

static uint16_t fw_le16(const uint8_t *p)
{
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}

static uint32_t fw_le32(const uint8_t *p)
{
    return (uint32_t)p[0] |
           ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

static fw_update_status_t fw_validate_package(fw_ctx_t *c)
{
    uint8_t trailer[FW_PACKAGE_TRAILER_BYTES];
    uint8_t i;
    uint16_t version;
    uint16_t project_id;
    uint32_t payload_bytes;
    uint16_t expected_crc;
    uint16_t expected_crc_inv;

    if ((c->package_tail_count != FW_PACKAGE_TRAILER_BYTES) ||
        (c->bytes_rx < FW_PACKAGE_TRAILER_BYTES))
    {
        return FW_UPDATE_ERR_IMAGE_FORMAT;
    }

    for (i = 0u; i < FW_PACKAGE_TRAILER_BYTES; i++)
    {
        trailer[i] = c->package_tail[(uint8_t)((c->package_tail_pos + i) %
                                               FW_PACKAGE_TRAILER_BYTES)];
    }

    if ((trailer[0] != FW_PACKAGE_MAGIC_0) || (trailer[1] != FW_PACKAGE_MAGIC_1) ||
        (trailer[2] != FW_PACKAGE_MAGIC_2) || (trailer[3] != FW_PACKAGE_MAGIC_3))
    {
        return FW_UPDATE_ERR_IMAGE_FORMAT;
    }

    version          = fw_le16(&trailer[4]);
    project_id       = fw_le16(&trailer[6]);
    payload_bytes    = fw_le32(&trailer[8]);
    expected_crc     = fw_le16(&trailer[12]);
    expected_crc_inv = fw_le16(&trailer[14]);

    if ((version != FW_PACKAGE_VERSION) ||
        (project_id != FW_PACKAGE_PROJECT_ID) ||
        (payload_bytes != (c->bytes_rx - FW_PACKAGE_TRAILER_BYTES)))
    {
        return FW_UPDATE_ERR_IMAGE_FORMAT;
    }
    if ((uint16_t)(expected_crc ^ expected_crc_inv) != UINT16_C(0xFFFF))
    {
        return FW_UPDATE_ERR_IMAGE_CRC;
    }
    return (expected_crc == c->package_crc) ? FW_UPDATE_OK : FW_UPDATE_ERR_IMAGE_CRC;
}

//-----------------------------------------------------------
// Program the current row buffer to the inactive partition and verify it.
// The remainder (if any) is padded with 0xFF first. Rows are written strictly
// sequentially, so the page containing a row is erased exactly when the row is
// the first of its 4 KB page (row_base_off page-aligned). Updates the running
// image CRC over the full (padded) row so it matches the later read-back CRC.
//-----------------------------------------------------------
static fw_update_status_t fw_flush_row( fw_ctx_t* c )
{
    uint32_t active_addr;
    uint32_t inactive_addr;
    dspic33ak_nvm_status_t s;

    while ( c->row_fill < DSPIC33AK_NVM_ROW_BYTES )
    {
        c->row.b[c->row_fill++] = 0xFFu;
    }

    active_addr   = DSPIC33AK_NVM_ACTIVE_BASE + c->row_base_off;
    inactive_addr = DSPIC33AK_NVM_TO_INACTIVE( active_addr );

    // Erase the page the first time we touch it (row_base_off is page-aligned
    // for the first row of every page, and rows arrive in order).
    if ( ( c->row_base_off % DSPIC33AK_NVM_PAGE_BYTES ) == 0u )
    {
        s = DSPIC33AK_NVM_PageErase( inactive_addr );
        c->last_wrec = DSPIC33AK_NVM_LastWrec();
        if ( s != DSPIC33AK_NVM_OK )
        {
            return FW_UPDATE_ERR_NVM;
        }
        c->pages_erased++;
    }

    s = DSPIC33AK_NVM_RowProgram( inactive_addr, c->row.w );
    c->last_wrec = DSPIC33AK_NVM_LastWrec();
    if ( s != DSPIC33AK_NVM_OK )
    {
        return FW_UPDATE_ERR_NVM;
    }

    s = DSPIC33AK_NVM_Verify( inactive_addr, c->row.b, DSPIC33AK_NVM_ROW_BYTES );
    if ( s != DSPIC33AK_NVM_OK )
    {
        return FW_UPDATE_ERR_NVM;
    }

    c->img_crc = xmodem_crc16_cont( c->img_crc, c->row.b, DSPIC33AK_NVM_ROW_BYTES );
    c->rows_programmed++;
    c->row_base_off += DSPIC33AK_NVM_ROW_BYTES;
    c->row_fill = 0u;
    return FW_UPDATE_OK;
}

//-----------------------------------------------------------
// XMODEM data sink: accept bytes strictly in order, fill rows, flush when full.
// Returns non-zero to abort the transfer; the specific reason is left in
// c->status so the caller can report it.
//-----------------------------------------------------------
static int fw_sink( uint32_t off, const uint8_t* data, uint16_t len, void* vctx )
{
    fw_ctx_t* c = (fw_ctx_t*)vctx;
    uint16_t  i;

    // We accumulate sequentially; the offset must match what we've accepted.
    if ( off != c->bytes_rx )
    {
        c->status = FW_UPDATE_ERR_XMODEM;
        return 1;
    }
    // Never let the image reach the final (BTSEQ) row.
    if ( ( (uint32_t)( c->bytes_rx ) + len ) > FW_MAX_IMAGE_BYTES )
    {
        c->status = FW_UPDATE_ERR_OVERFLOW;
        return 1;
    }

    for ( i = 0u; i < len; i++ )
    {
        fw_package_track_byte(c, data[i]);
        c->row.b[c->row_fill++] = data[i];
        if ( c->row_fill == DSPIC33AK_NVM_ROW_BYTES )
        {
            fw_update_status_t s = fw_flush_row( c );
            if ( s != FW_UPDATE_OK )
            {
                c->status = s;
                return 1;
            }
        }
    }

    c->bytes_rx += len;
    return 0;
}

//-----------------------------------------------------------
// Read the programmed span back word by word and CRC-16 it. PASS iff it matches
// the running image CRC. Proves the inactive-alias read-back path on silicon.
//-----------------------------------------------------------
static fw_update_status_t fw_readback_crc( fw_ctx_t* c, uint16_t* out_crc )
{
    uint32_t total = c->rows_programmed * DSPIC33AK_NVM_ROW_BYTES;
    uint32_t a;
    uint16_t crc = 0u;

    for ( a = 0u; a < total; a += DSPIC33AK_NVM_WORD_BYTES )
    {
        uint32_t w[DSPIC33AK_NVM_U32_PER_WORD];
        uint32_t inactive_addr = DSPIC33AK_NVM_TO_INACTIVE( DSPIC33AK_NVM_ACTIVE_BASE + a );
        if ( DSPIC33AK_NVM_ReadWord( inactive_addr, w ) != DSPIC33AK_NVM_OK )
        {
            return FW_UPDATE_ERR_NVM;
        }
        crc = xmodem_crc16_cont( crc, (const uint8_t*)w, DSPIC33AK_NVM_WORD_BYTES );
    }

    *out_crc = crc;
    return ( crc == c->img_crc ) ? FW_UPDATE_OK : FW_UPDATE_ERR_READBACK;
}

//-----------------------------------------------------------
// Flush any partial final row, require >= 1 row, then read-back-verify.
//-----------------------------------------------------------
static fw_update_status_t fw_finalize( fw_ctx_t* c, uint16_t* readback_crc )
{
    *readback_crc = 0u;

    if ( c->status != FW_UPDATE_OK )
    {
        return c->status;                       // the sink already failed
    }
    c->status = fw_validate_package(c);
    if (c->status != FW_UPDATE_OK)
    {
        return c->status;
    }
    if ( c->row_fill > 0u )
    {
        fw_update_status_t s = fw_flush_row( c );
        if ( s != FW_UPDATE_OK )
        {
            c->status = s;
            return s;
        }
    }
    if ( c->rows_programmed == 0u )
    {
        c->status = FW_UPDATE_ERR_XMODEM;       // nothing arrived
        return c->status;
    }

    c->status = fw_readback_crc( c, readback_crc );
    return c->status;
}

static void fw_fill_result( const fw_ctx_t* c, uint16_t readback_crc, fw_update_result_t* out )
{
    if ( out == NULL )
    {
        return;
    }
    out->status          = c->status;
    out->bytes_rx        = c->bytes_rx;
    out->pages_erased    = c->pages_erased;
    out->rows_programmed = c->rows_programmed;
    out->img_crc         = c->img_crc;
    out->readback_crc    = readback_crc;
    out->package_crc     = c->package_crc;
    out->last_wrec       = c->last_wrec;
}

//-----------------------------------------------------------
// Public API
//-----------------------------------------------------------
fw_update_status_t fw_update_receive( fw_update_result_t* out )
{
    uint16_t        readback_crc = 0u;
    uint32_t        rx           = 0u;
    xmodem_status_t xs;

    fw_ctx_reset( &s_ctx );
    s_last_receive_good = false;                // invalidate any prior commit gate

    // The caller invokes this from the foreground command processor and pauses
    // all periodic application output first. While this blocking function owns
    // UART1, no printf/write path may run: XMODEM control bytes (C/ACK/NAK) must
    // be the only board-to-host traffic until the transfer finishes.

    xs = xmodem_receive( fw_sink, &s_ctx, &rx );

    if ( s_ctx.status != FW_UPDATE_OK )
    {
        // The sink aborted; its reason is already in s_ctx.status. Nothing more.
    }
    else if ( xs != XMODEM_OK )
    {
        s_ctx.status = FW_UPDATE_ERR_XMODEM;
    }
    else
    {
        (void)fw_finalize( &s_ctx, &readback_crc );
    }

    // Arm the commit gate ONLY for a receive that finished OK -- the inactive
    // partition now holds a project-tagged, CRC/read-back-verified image.
    s_last_receive_good = ( s_ctx.status == FW_UPDATE_OK );

    fw_fill_result( &s_ctx, readback_crc, out );
    return s_ctx.status;
}
