#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/*
 * app_config.h
 * ------------
 * Application-level demo behavior toggles for the dspic33ak-hal-starter firmware.
 *
 * These are APPLICATION choices (what the starter firmware does), NOT board facts.
 * Board pin/peripheral facts live in board_pins.h / board.h. Keep build-time demo
 * switches here so they are separate from the board description.
 */

/*
 * SPI1 framed-mode (TDM8) smoke demo -- default ON.
 *
 * When 1 (default): after the existing starter demos come up, the firmware also starts a
 * codec-less SPI1 TDM8 self-clocked master on MikroBUS-A (FS=RP70, BCLK=RP75,
 * DataOut=RP101, DataIn=RP106) and prints a one-line TDM status every ~5 s. The stream
 * runs autonomously on DMA/ISR; a start failure is reported but does NOT stop the rest of
 * the starter.
 *
 * Set to 0 to restore the classic starter firmware and FREE the MikroBUS-A SPI pins
 * (e.g. to plug in a real SPI Click board). The MikroBUS-A I2C SDA/SCL pins are different
 * and are unaffected either way.
 */
#ifndef HAL_STARTER_ENABLE_TDM_SMOKE_DEMO
#define HAL_STARTER_ENABLE_TDM_SMOKE_DEMO 1
#endif

/*
 * EXPERIMENT: 50%-duty FS/LRCK on the TDM8 master, generated by CLC10 -- default OFF.
 *
 * Branch exp/tdm-master-clc10-fs50. When 0 (default) the TDM8 smoke demo behaves exactly
 * as before: SPI1 framed-mode drives FS(SS1) directly onto RP70 as a one-word-wide pulse
 * once per 8-word frame (256 BCLK period).
 *
 * When 1, the experiment leaves BCLK/DATA untouched but replaces the externally-observed
 * FS with a ~50%-duty signal built by CLC10:
 *   - SPI1 emits a SHORT FSYNC marker every 4 words (128 BCLK) -- FRMCNT=2, FRMSYPW=0.
 *   - That FSYNC (SS1) is routed INTERNALLY (no jumper) to virtual pin RPV8.
 *   - CLC10 is a J-K flip-flop (J=K=1) clocked by RPV8 -> toggles every 128 BCLK.
 *   - CLC10OUT is routed to the external FS pin RP70 instead of SS1.
 * Result: FS period = 256 BCLK, duty ~50%, BCLK/FS ~256 (unchanged audio frame rate).
 *
 * The data path (DMA geometry, block callback, SDO/SDI/BCLK) is NOT changed; only the
 * FS-pulse cadence and the RP70 PPS source differ. Requires HAL_STARTER_ENABLE_TDM_SMOKE_DEMO.
 */
#ifndef APP_TDM_MASTER_FS50_BY_CLC10
#define APP_TDM_MASTER_FS50_BY_CLC10 1   /* experiment branch: ON (HW-verified). 0 = stock TDM8 FS */
#endif

/*
 * DIAGNOSTIC: bypass the J-K flip-flop -- configure CLC10 as a transparent passthrough of
 * its Gate1 data (the SS1 FSYNC marker) instead of a toggle. 0 = normal 50%-FS toggle.
 * Set to 1 to prove the SS1 -> RPV8 -> CLC10 -> CLC10OUT -> RP70 routing works END-TO-END
 * independently of the flip-flop logic: in bypass, RP70 should show the SS1 marker itself
 * (a ~98 kHz narrow-pulse train at FRMCNT=2). If RP70 toggles in bypass but not in toggle
 * mode, the routing is fine and the J-K configuration is the suspect.
 */
#ifndef APP_TDM_MASTER_FS50_CLC10_BYPASS
#define APP_TDM_MASTER_FS50_CLC10_BYPASS 0
#endif

/*
 * FS polarity (CLC10 output) for the experiment. 0 = CLC10 LCPOL off (FS starts Low after
 * the init reset -> slots 0..3 during the FS-Low half, slots 4..7 during the FS-High half).
 * Set to 1 to invert (LCPOL on) if the downstream receiver expects the opposite LRCK phase.
 */
#ifndef APP_TDM_MASTER_FS50_CLC10_INVERT
#define APP_TDM_MASTER_FS50_CLC10_INVERT 0
#endif

#endif /* APP_CONFIG_H */
