#include "fw_command.h"

#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include "nora_uart.h"
#include "nora_tick_timer.h"
#include "fw_update.h"
#include "fw_btseq.h"
#include "fw_uca.h"
#include "led_sw.h"
#include "app_config.h"
#if HAL_STARTER_ENABLE_TDM_SMOKE_DEMO
#include "tdm_smoke.h"
#endif

#define COMMAND_UART               NORA_UART_INST_1
#define COMMAND_LINE_CAPACITY      32u
#define COMMAND_MAX_BYTES_PER_POLL 96u
#define RAW_FILE_IDLE_MS           500u

static char     s_line[COMMAND_LINE_CAPACITY];
static uint8_t  s_line_len;
static bool     s_last_was_cr;
static bool     s_quiet;
static bool     s_raw_discard;
static uint32_t s_raw_last_ms;

static void echo_byte(uint8_t c)
{
    (void)nora_uart_write_byte(COMMAND_UART, c);
}

static void echo_newline(void)
{
    echo_byte((uint8_t)'\r');
    echo_byte((uint8_t)'\n');
}

static char ascii_lower(char c)
{
    if ((c >= 'A') && (c <= 'Z')) {
        return (char)(c + ('a' - 'A'));
    }
    return c;
}

static void line_reset(void)
{
    s_line_len = 0u;
    s_line[0] = '\0';
}

static const char *update_status_name(fw_update_status_t status)
{
    switch (status) {
    case FW_UPDATE_OK:           return "ok";
    case FW_UPDATE_ERR_XMODEM:   return "xmodem";
    case FW_UPDATE_ERR_NVM:      return "flash";
    case FW_UPDATE_ERR_OVERFLOW: return "image too large";
    case FW_UPDATE_ERR_IMAGE_FORMAT: return "wrong reflash image format";
    case FW_UPDATE_ERR_IMAGE_CRC:    return "reflash image crc";
    case FW_UPDATE_ERR_READBACK: return "read-back crc";
    default:                     return "unknown";
    }
}

static const char *commit_status_name(fw_commit_status_t status)
{
    switch (status) {
    case FW_COMMIT_OK:               return "ok";
    case FW_COMMIT_ERR_NOT_VERIFIED: return "no validated image";
    case FW_COMMIT_ERR_WRAP:         return "boot sequence exhausted";
    case FW_COMMIT_ERR_NVM:          return "flash";
    case FW_COMMIT_ERR_VERIFY:       return "boot sequence read-back";
    case FW_COMMIT_ERR_ROLLBACK:     return "boot sequence rollback";
    case FW_COMMIT_ERR_UCA:          return "inactive partition config";
    default:                         return "unknown";
    }
}

static void print_receive_result(const fw_update_result_t *result)
{
    if (result->status == FW_UPDATE_OK) {
        printf("\r\nFirmware receive: PASS\r\n");
        printf("  bytes        : %lu\r\n", (unsigned long)result->bytes_rx);
        printf("  pages erased : %lu\r\n", (unsigned long)result->pages_erased);
        printf("  rows written : %lu\r\n", (unsigned long)result->rows_programmed);
        printf("  image crc    : %04X\r\n", (unsigned)result->img_crc);
        printf("  read-back crc: %04X\r\n", (unsigned)result->readback_crc);
        printf("  payload crc  : %04X\r\n", (unsigned)result->payload_crc);
        printf("Validation: PASS (DBFW manifest + xmodem-crc + flash read-back)\r\n");
        printf("Type *fca5 to activate the validated partition.\r\n");
        return;
    }

    printf("\r\nFirmware receive: FAIL (%s, wrec=%02X)\r\n",
           update_status_name(result->status), (unsigned)result->last_wrec);
    printf("  bytes received: %lu\r\n", (unsigned long)result->bytes_rx);
    if (result->status == FW_UPDATE_ERR_XMODEM) {
        printf("Use Tera Term: File > Transfer > XMODEM > Send.\r\n");
        printf("Do not use File > Send file. Type *fua5 to retry.\r\n");
    } else if ((result->status == FW_UPDATE_ERR_IMAGE_FORMAT) ||
               (result->status == FW_UPDATE_ERR_IMAGE_CRC)) {
        printf("Send reflash_image.bin generated by this project's build.ps1.\r\n");
        printf("Regenerate it if the firmware and the file are from different builds.\r\n");
        printf("The inactive partition was not validated; *fca5 is blocked.\r\n");
    } else {
        printf("The inactive partition was not validated; *fca5 is blocked.\r\n");
    }
}

// Read-only: which physical partition is active right now, both BTSEQ words, and
// each side's UCA validation -- the runtime equivalent of the boot banner's "bank"
// line, without needing a reset to see it again.
static void print_partition_status(void)
{
    fw_uca_report_t act_uca;
    fw_uca_report_t ina_uca;
    bool            p2        = NORA_NVM_IsPartition2Active();
    uint16_t        act_seq   = fw_btseq_read_active_seq();
    uint16_t        ina_seq   = fw_btseq_read_inactive_seq();
    fw_uca_status_t act_status = fw_uca_validate_active(&act_uca);
    fw_uca_status_t ina_status = fw_uca_validate_inactive(&ina_uca);

    printf("\r\n\"?fp\" bank     : P%u active, BTSEQ=0x%03X (inactive P%u, BTSEQ=0x%03X)\r\n",
           p2 ? 2u : 1u, (unsigned)act_seq, p2 ? 1u : 2u, (unsigned)ina_seq);
    printf("\"?fp\" active   : UCA %s (ALTI2C2=%s, BOOTSWP=%s)\r\n",
           fw_uca_status_name(act_status),
           act_uca.alti2c2_on ? "ON" : "OFF",
           act_uca.bootswp_enabled ? "ENABLED" : "DISABLED");
    printf("\"?fp\" inactive : UCA %s (ALTI2C2=%s, BOOTSWP=%s)\r\n",
           fw_uca_status_name(ina_status),
           ina_uca.alti2c2_on ? "ON" : "OFF",
           ina_uca.bootswp_enabled ? "ENABLED" : "DISABLED");
}

// Transfer progress on the 8 user LEDs, as a bar that grows from LED7 toward LED0
// (matching the board's physical left-to-right orientation).
//
// This is the display side of fw_update's progress hook. LEDs are used rather than
// the console because xmodem_receive() owns UART1 for the whole transfer: the
// sender is waiting for ACK/NAK, so printing progress characters there would
// corrupt the protocol (and a terminal in XMODEM-send mode consumes them as
// protocol bytes rather than displaying them anyway). The LEDs are free during an
// update -- the heartbeat that normally owns LED0 is gated off while quiet.
//
// The bar is deliberately NOT cleared when the transfer ends: a full bar means the
// whole payload arrived, and a partial bar shows how far a failed transfer got,
// which is useful at a glance. LED0 returns to heartbeat duty after *tq0001.
static void update_progress_leds(uint32_t done, uint32_t total)
{
    uint8_t lit;
    uint8_t i;

    if (total == 0u) {
        return;                 /* manifest not parsed yet; nothing to scale against */
    }
    /* done <= total <= FW_MAX_IMAGE_BYTES (0x3FE00), so done * 8 cannot overflow. */
    lit = (uint8_t)((done * (uint32_t)LED_SW_LED_COUNT) / total);
    /* Fill from the LED7 end: LED7 lights first, LED0 last. */
    for (i = 0u; i < LED_SW_LED_COUNT; i++) {
        led_sw_set(i, (i >= (uint8_t)(LED_SW_LED_COUNT - lit)));
    }
}

// Mechanically restart the TDM/DMA smoke stream after an attempt that leaves the
// active partition unchanged (a failed receive, or a failed commit). This is a
// hardware-safety action, not a console-noise decision -- it must run regardless of
// the print-quiet flag, or the demo would stay silently dead until reset.
static void restart_tdm_after_failed_attempt(void)
{
#if HAL_STARTER_ENABLE_TDM_SMOKE_DEMO
    if (!tdm_smoke_resume_after_update_failure()) {
        printf("WARNING: TDM demo restart failed (%s); reset the board.\r\n",
               tdm_smoke_last_error_str());
    }
#endif
}

static void receive_firmware(void)
{
    fw_update_result_t result;

    /* Quiet is one-way from here: neither a successful nor a failed receive
     * clears it. Only an explicit *tq0001, or a reset (a successful *fca5
     * commit), brings periodic output back. */
    s_quiet = true;
#if HAL_STARTER_ENABLE_TDM_SMOKE_DEMO
    /* The smoke stream runs autonomously on DMA/ISR. Stop it before any erase or
     * program operation so CPU stalls cannot leave transport state ambiguous. */
    if (!tdm_smoke_pause_for_update()) {
        printf("\r\nFirmware update refused: TDM/DMA could not be stopped.\r\n");
        printf("Reset the board before retrying.\r\n");
        s_quiet = false;
        return;
    }
#endif
    printf("\r\nFirmware update armed.\r\n");
    printf("Tera Term: File > Transfer > XMODEM > Send\r\n");
    printf("Select reflash_image.bin (1K may be checked or unchecked).\r\n");
    printf("LED7..LED0 show transfer progress as a bar.\r\n");
    printf("Waiting for xmodem-crc data on UART1...\r\n");

    /* Start from an empty bar, then let the hook grow it as blocks land. */
    led_sw_all(false);
    fw_update_set_progress(update_progress_leds);
    (void)fw_update_receive(&result);
    fw_update_set_progress(NULL);
    print_receive_result(&result);
    if (result.status != FW_UPDATE_OK) {
        restart_tdm_after_failed_attempt();
        printf("Type *fua5 to retry.\r\n");
    }
    printf("Periodic starter output stays off. Type *tq0001 to resume it.\r\n");
}

static void commit_firmware(void)
{
    fw_commit_status_t status;

    if (!fw_update_receive_verified()) {
        printf("\r\nCommit refused: no validated image. Run *fua5 first.\r\n");
        return;
    }

    printf("\r\nCommitting validated partition; the board will reset...\r\n");
    status = fw_commit();

    /* Success resets and never returns. */
    if (status == FW_COMMIT_ERR_ROLLBACK) {
        printf("Commit failed: %s. Do not reset or power-cycle; service is required.\r\n",
               commit_status_name(status));
    } else {
        printf("Commit failed: %s. Current partition remains selected.\r\n",
               commit_status_name(status));
        if (status == FW_COMMIT_ERR_UCA) {
            printf("Flash a newly verified production.bundle.hex before retrying.\r\n");
        } else if (status == FW_COMMIT_ERR_WRAP) {
            printf("BTSEQ generations are exhausted; PKOB4 service is required.\r\n");
        } else {
            printf("Run *fua5 and transfer reflash_image.bin again before retrying.\r\n");
        }
    }
    restart_tdm_after_failed_attempt();
    printf("Periodic starter output stays off. Type *tq0001 to resume it.\r\n");
}

static void process_line(void)
{
    uint8_t i;

    s_line[s_line_len] = '\0';
    for (i = 0u; i < s_line_len; i++) {
        s_line[i] = ascii_lower(s_line[i]);
    }

    if (s_line_len == 0u) {
        return;
    }
    if (strcmp(s_line, "*fua5") == 0) {
        receive_firmware();
        return;
    }
    if (strcmp(s_line, "*fca5") == 0) {
        commit_firmware();
        return;
    }
    if ((strcmp(s_line, "*fu") == 0) || (strcmp(s_line, "*fc") == 0)) {
        printf("Command is not armed. Use *fua5 or *fca5.\r\n");
        return;
    }
    if (strcmp(s_line, "?fp") == 0) {
        print_partition_status();
        return;
    }
    if (strcmp(s_line, "*tq0001") == 0) {
        s_quiet = false;
        printf("\"*tq\" periodic starter output ON\r\n");
        return;
    }
    if (strcmp(s_line, "*tq0000") == 0) {
        s_quiet = true;
        printf("\"*tq\" periodic starter output OFF\r\n");
        return;
    }

    /* Spell out the *tq polarity here: the payload is the output enable, so 0000
     * silences and 0001 restores. Discovering that from the console beats having
     * to find it in the guide. */
    printf("Unknown command. Commands: *fua5, *fca5, ?fp,\r\n");
    printf("  *tq0000 (periodic output off) / *tq0001 (on)\r\n");
}

static void begin_raw_file_discard(void)
{
    line_reset();
    s_raw_discard = true;
    s_raw_last_ms = nora_tick_timer_get_ms();
    printf("\r\nWARNING: plain file data was detected and discarded.\r\n");
    printf("Do not use Tera Term File > Send file.\r\n");
    printf("Type *fua5, then use File > Transfer > XMODEM > Send.\r\n");
}

static void feed_normal_byte(uint8_t c)
{
    if ((c == (uint8_t)'\r') || (c == (uint8_t)'\n')) {
        if ((c == (uint8_t)'\n') && s_last_was_cr) {
            s_last_was_cr = false;
            return;
        }
        s_last_was_cr = (c == (uint8_t)'\r');
        echo_newline();
        process_line();
        line_reset();
        return;
    }

    s_last_was_cr = false;

    if ((c == 0x08u) || (c == 0x7Fu)) {
        if (s_line_len > 0u) {
            s_line_len--;
            s_line[s_line_len] = '\0';
            echo_byte(0x08u);
            echo_byte((uint8_t)' ');
            echo_byte(0x08u);
        }
        return;
    }

    if ((c < 0x20u) || (c > 0x7Eu)) {
        begin_raw_file_discard();
        return;
    }

    if (s_line_len >= (COMMAND_LINE_CAPACITY - 1u)) {
        begin_raw_file_discard();
        return;
    }

    s_line[s_line_len++] = (char)c;
    s_line[s_line_len] = '\0';
    echo_byte(c);
}

void fw_command_init(void)
{
    line_reset();
    s_last_was_cr = false;
    s_quiet = false;
    s_raw_discard = false;
    s_raw_last_ms = 0u;
}

bool fw_command_quiet(void)
{
    return s_quiet || s_raw_discard;
}

void fw_command_poll(void)
{
    uint8_t data;
    uint8_t count = 0u;
    bool received = false;

    while ((count < COMMAND_MAX_BYTES_PER_POLL) &&
           nora_uart_rx_ready(COMMAND_UART)) {
        if (nora_uart_read_byte(COMMAND_UART, &data) != NORA_UART_OK) {
            break;
        }
        count++;
        received = true;

        if (s_raw_discard) {
            s_raw_last_ms = nora_tick_timer_get_ms();
            continue;
        }
        feed_normal_byte(data);
    }

    if (s_raw_discard && !received &&
        ((uint32_t)(nora_tick_timer_get_ms() - s_raw_last_ms) >= RAW_FILE_IDLE_MS)) {
        nora_uart_rx_flush(COMMAND_UART);
        s_raw_discard = false;
        s_last_was_cr = false;
        printf("Plain file input cleared. Ready for *fua5.\r\n");
    }
}
